---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-app
  namespace: default
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30088
      port: 10777
      targetPort: api
  selector:
    app: proxy-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-app
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: proxy-app
      version: "1"
  template:
    metadata:
      labels:
        app: proxy-app
        version: "1"
    spec:
      containers:
        - name: proxy-app
          image: avhost/go-apiproxy
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 10777
          env:
            - name: API_URL
              value: http://az-otus-echo-go.default.svc.cluster.local:8000
            - name: API_TOKEN
              value: any
