---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32080
      targetPort: 8000
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello-world
      version: "1"
  template:
    metadata:
      labels:
        app: hello-world
        version: "1"
    spec:
      containers:
        - name: hello-world
          image: tipsypenguin/hello-world
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000