---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса

---
apiVersion: v1
kind: Service
metadata:
  name: projects-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32080
      targetPort: 5000
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: projects-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-service
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: projects-service
      version: "1"
  template:
    metadata:
      labels:
        app: projects-service
        version: "1"
    spec:
      containers:
        - name: projects-service
          image: vladraven/otus_istio_projects_service
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---

# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: projects-service
#   labels: 
#     app: projects-service
#     version: "1"
# spec:
#   jobLabel: projects-service
#   namespaceSelector:
#     matchNames:
#     - default
#   selector:
#     matchLabels:
#       app: projects-service
#       version: "1"
#   endpoints:
#   - interval: 15s
#     port: web
#     path: /metrics