apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.apiGateway.nodePort }}
      targetPort: "http"
      protocol: TCP
      name: "http"
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}  